// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mob_Killer.Data;

namespace Mob_Killer.Migrations
{
    [DbContext(typeof(MobKillerDbContext))]
    [Migration("20191118111434_AddAll")]
    partial class AddAll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Mob_Killer.Entities.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseAttack")
                        .HasColumnType("REAL");

                    b.Property<double>("BonusEvasion")
                        .HasColumnType("REAL");

                    b.Property<string>("NameItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdItem");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Mob_Killer.Entities.Joueur", b =>
                {
                    b.Property<int>("IdJoueur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EvasionJoueur")
                        .HasColumnType("REAL");

                    b.Property<double>("HealthJoueur")
                        .HasColumnType("REAL");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameJoueur")
                        .HasColumnType("TEXT");

                    b.HasKey("IdJoueur");

                    b.HasIndex("ItemId");

                    b.ToTable("Joueur");
                });

            modelBuilder.Entity("Mob_Killer.Entities.Monstre", b =>
                {
                    b.Property<int>("IdMonstre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AttackMonstre")
                        .HasColumnType("REAL");

                    b.Property<double>("EvasionMonstre")
                        .HasColumnType("REAL");

                    b.Property<double>("HealthMonste")
                        .HasColumnType("REAL");

                    b.Property<string>("NameMonstre")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMonstre");

                    b.ToTable("Monstre");
                });

            modelBuilder.Entity("Mob_Killer.Entities.Joueur", b =>
                {
                    b.HasOne("Mob_Killer.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
